server:
  port: 9090

spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: zulip
            client-secret: GS3aPWfTqNJ7sT8ONhscmzCR9jPmgBf2
            scope: openid,profile
            authorization-grant-type: password
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/infra
            user-name-attribute: preferred_username

keycloak:
  server-url: http://localhost:8080/auth
  realm: infra
  username: admin
  password: admin

