spring:
  application:
    name: bff
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: YOUR_CLIENT_ID
            client-secret: YOUR_CLIENT_SECRET
            scope: openid,profile,email
            authorization-grant-type: authorization_code
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/demo-realm
            authorization-uri: http://localhost:8080/realms/demo-realm/protocol/openid-connect/auth
            token-uri: http://localhost:8080/realms/demo-realm/protocol/openid-connect/token
            user-info-uri: http://localhost:8080/realms/demo-realm/protocol/openid-connect/userinfo
            jwk-set-uri: http://localhost:8080/realms/demo-realm/protocol/openid-connect/certs

